@keycloakUrl=http://localhost:8080
@keycloakRealm=<keycloakRealm>
@keycloakClientId=<keycloakClientId>
@keycloakSecret=<keycloakSecret>
@baseUrl=http://localhost:8000
@accessToken=<access_token>

### Get Access Token
POST {{keycloakUrl}}/realms/{{keycloakRealm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{keycloakClientId}}&username=matthew&password=matthew&grant_type=password&client_secret={{keycloakSecret}}

### Health 
GET {{baseUrl}}/health

### Minio
GET {{baseUrl}}/minio
Authorization: Bearer {{accessToken}}

### Private
GET {{baseUrl}}/private
Authorization: Bearer {{accessToken}}

### Admin role only
GET {{baseUrl}}/admin
Authorization: Bearer {{accessToken}}

### Standard role only
GET {{baseUrl}}/standard
Authorization: Bearer {{accessToken}} 
 